@echo off
if not exist "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps-v2\assets\images\icon" mkdir "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps-v2\assets\images\icon"
copy "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps\assets\images\icon\absensi.png" "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps-v2\assets\images\icon\"
copy "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps\assets\images\icon\approval.png" "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps-v2\assets\images\icon\"
copy "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps\assets\images\icon\rencanakerja.png" "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps-v2\assets\images\icon\"
copy "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps\assets\images\icon\permintaan.png" "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps-v2\assets\images\icon\"
copy "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps\assets\images\icon\tugas.png" "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps-v2\assets\images\icon\"
copy "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps\assets\images\icon\pengajuan.png" "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps-v2\assets\images\icon\"
copy "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps\assets\images\icon\administrasi.png" "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps-v2\assets\images\icon\"
copy "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps\assets\images\icon\arsip.png" "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps-v2\assets\images\icon\"
copy "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps\assets\images\icon\selamat_bergabung.svg" "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps-v2\assets\images\icon\"
copy "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps\assets\images\icon\Peraturan Perusahaan.png" "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps-v2\assets\images\icon\"
copy "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps\assets\images\icon\fill-biodata.png" "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps-v2\assets\images\icon\"
copy "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps\assets\images\icon\home-poin.png" "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps-v2\assets\images\icon\"
copy "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps\assets\images\icon\profile_kosong.webp" "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps-v2\assets\images\icon\"
copy "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps\assets\images\maha-blur.png" "c:\WorkSpace\Personal\Flutter\.MAHA\maha-apps-v2\assets\images\"
